server:
  port: 8081
  shutdown: graceful

spring:
  application:
    name: app-server
  lifecycle:
    timeout-per-shutdown-phase: 15s

management:
  endpoints:
        web:
            exposure:
                include: health

logging:
  level:
    root: INFO
    com.erojas.lab.appserver: DEBUG