server:
  port: 8081

spring:
  application:
    name: app-server

logging:
  level:
    root: INFO
    com.erojas.lab.appserver: DEBUG

---
spring:
  config:
    activate:
      on-profile: docker

server:
  port: 8080