apiVersion: v1
kind: Service
metadata:
  name: app-server
  labels:
    app: app-server
spec:
  type: ClusterIP
  selector:
    app: app-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
